jobs:
  - job: create_azure_rg_job
    steps:
          - task: AzureCLI@2
            displayName: 'Create Azure RG'
            inputs:
              azureSubscription: 'AzureLabDev(2f858c57-6594-463c-b525-a5d7afec60cf)'
              scriptType: bash
              scriptLocation: inlineScript
              addSpnToEnvironment: true
              inlineScript: |
                #!/usr/bin/env bash
 
                az group create -l southeastasia -n $(RGNAME)