# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)
 
trigger:
  batch: true
  branches:
    include:
    - azure-varoable


#pool:
#  vmImage: ubuntu-latest

#steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'

stages:
- stage: create_variables_stage
  jobs:
  - job: create_variables_job
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureLabDev(2f858c57-6594-463c-b525-a5d7afec60cf)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          #!/bin/bash
          #VNET_RESOURCE_ID=$(az network vnet show --resource-group "thomasthorntoncloud-ado-agent" --name "thomasthorntoncloud-ado-agent-vnet" --query "id" -o tsv)
          #VNET_LOCATION=$(az network vnet show --resource-group "thomasthorntoncloud-ado-agent" --name "thomasthorntoncloud-ado-agent-vnet" --query "location" -o tsv)
          VNET_RESOURCE_ID="vnet1" 
          VNET_LOCATION="Southeastasia"
          echo "Setting variable #VNET_RESOURCE_ID_SET"
          echo "##vso[task.setvariable variable=VNET_RESOURCE_ID_SET;isOutput=true]$VNET_RESOURCE_ID"
           
          echo "Setting variable VNET_LOCATION_SET"
          echo "##vso[task.setvariable variable=VNET_LOCATION_SET;isOutput=true]$VNET_LOCATION"
- stage: variables_stage_output
  jobs:
  - job: variables_stage_output_job
    variables:
      VNET_RESOURCE_ID_SET: $[stageDependencies.create_variables_stage.create_variables_job.outputs['ADO_variables.VNET_RESOURCE_ID_SET']]
      VNET_LOCATION_SET: $[stageDependencies.create_variables_stage.create_variables_job.outputs['ADO_variables.VNET_LOCATION_SET']]
    steps:
      - task: Bash@3
        displayName: 'Output new ADO Variables'
        inputs:
          targetType: inline
          script: |
            echo "VNET Resource ID is: $VNET_RESOURCE_ID_SET"
 
            echo "VNET Location is: $VNET_LOCATION_SET"
