name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

trigger: none


variables:
  - name: backendServiceArm
    value: 'thomasthorntoncloud'
  - name: backendAzureRmResourceGroupName
    value: 'thomasthorntoncloud'
  - name: backendAzureRmStorageAccountName
    value: 'thomasthorntontfstate'
  - name: backendAzureRmContainerName
    value: 'adovariableottf'
  - name: backendAzureRmKey
    value: 'terraform.tfstate'
  - name: environment
    value: 'production'
  - name: name
    value: 'tamops'

stages :
  - stage: terraform
    jobs:
    - job: validate
      continueOnError: false
      steps:
      #- task: TerraformInstaller@0
      #  displayName: 'install'
      #  inputs:
      #    terraformVersion: '1.1.7'
      - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
        inputs:
          terraformVersion: '0.12.3'
      - task: TerraformTaskV2@2
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/Azure-DevOps-Variables-to-Terraform-Variables/terraform/'
          backendServiceArm: 'AzureLabDev(2f858c57-6594-463c-b525-a5d7afec60cf)'
          backendAzureRmResourceGroupName: 'terraformlcaodev1-rg'
          backendAzureRmStorageAccountName: 'terraformlcaodev1stg'
          backendAzureRmContainerName: 'terraform'
          backendAzureRmKey: 'terraform1.tfstate'
      - task: TerraformTaskV2@2
        displayName: 'validate'
        inputs:
          provider: 'azurerm'
          command: 'validate'
          workingDirectory: '$(System.DefaultWorkingDirectory)/Azure-DevOps-Variables-to-Terraform-Variables/terraform/'

      - task: TerraformTaskV2@2
        displayName: 'plan'
        inputs:
          provider: 'azurerm'
          command: 'plan'
          commandOptions: '-input=false -var name=$(name) -var environment=$(Environment) -var-file="../terraform/environments/$(Environment)/$(Environment)-ado-variables.tfvars"'
          environmentServiceNameAzureRM: 'AzureLabDev(2f858c57-6594-463c-b525-a5d7afec60cf)'
          workingDirectory: '$(System.DefaultWorkingDirectory)/Azure-DevOps-Variables-to-Terraform-Variables/terraform/'      
 
      # - task: TerraformTaskV2@2
      #   displayName: 'apply'
      #   inputs:
      #     provider: 'azurerm'
      #     command: 'apply'
      #     commandOptions: '-input=false -var name=$(name) -var environment=$(Environment) -var-file="../terraform/environments/$(Environment)/$(Environment).tfvars"'
      #     environmentServiceNameAzureRM: 'thomasthorntoncloud'
      #     workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'