name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

trigger: none


variables:
  - name: backendServiceArm
    value: 'AzureLabDev(2f858c57-6594-463c-b525-a5d7afec60cf)'
  - name: backendAzureRmResourceGroupName
    value: 'terraformlcaodev1-rg'
  - name: backendAzureRmStorageAccountName
    value: 'terraformlcaodev1stg'
  - name: backendAzureRmContainerName
    value: 'terraform'
  - name: backendAzureRmKey
    value: 'terraform.tfstate'
  - name: environment
    value: 'production'
  - name: name
    value: 'azuredevops1-rg'

stages :
  - stage: terraform
    jobs:
    - job: validate
      continueOnError: false
      steps:
      #- task: TerraformInstaller@0
      #  displayName: 'install'
      #  inputs:
      #    terraformVersion: '1.1.7'
      - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
        inputs:
          terraformVersion: '0.12.3'
      - task: TerraformTaskV2@2
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/Azure-DevOps-Variables-to-Terraform-Variables/terraform/'
          backendServiceArm: '$(backendServiceArm)'#'AzureLabDev(2f858c57-6594-463c-b525-a5d7afec60cf)'
          backendAzureRmResourceGroupName: '$(backendAzureRmResourceGroupName)'
          backendAzureRmStorageAccountName: '$(backendAzureRmStorageAccountName)'
          backendAzureRmContainerName: '$(backendAzureRmContainerName)'
          backendAzureRmKey: '$(backendAzureRmKey)'
      - task: TerraformTaskV2@2
        displayName: 'validate'
        inputs:
          provider: 'azurerm'
          command: 'validate'
          workingDirectory: '$(System.DefaultWorkingDirectory)/Azure-DevOps-Variables-to-Terraform-Variables/terraform/'

      - task: TerraformTaskV2@2
        displayName: 'plan'
        inputs:
          provider: 'azurerm'
          command: 'plan'
          commandOptions: '-input=false -var name=$(name) -var environment=$(Environment) -var-file="../terraform/environments/$(Environment)/$(Environment)-ado-variables.tfvars"'
          environmentServiceNameAzureRM: '$(backendServiceArm)'
          workingDirectory: '$(System.DefaultWorkingDirectory)/Azure-DevOps-Variables-to-Terraform-Variables/terraform/'
 
      - task: TerraformTaskV2@2
        displayName: 'apply'
        inputs:
            provider: 'azurerm'
            command: 'apply'
            commandOptions: '-input=false -var name=$(name) -var environment=$(Environment) -var-file="../terraform/environments/$(Environment)/$(Environment).tfvars"'
            environmentServiceNameAzureRM: '$(backendServiceArm)'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Azure-DevOps-Variables-to-Terraform-Variables/terraform/'